### ISSUE TITLE
causal-ml package to-do list

### ISSUE THREAD

**Issue by jialul** [jialul/evalITR#1]
# Causal ML package to-do
## General issues
- [ ] write up the documentations for the package
- [ ] add examples (micro-finance or star)
- [ ] clean up the functions for binary outcomes
